public  class checkDatatypes {
    public void MethodBoolean(){
        Boolean checkBoolean = true;
        System.debug(checkBoolean);
    }
    public void MethodInteger(){
        integer varfirst = 1;
        Integer varsecond= 2;
        system.debug(varfirst);
        system.debug(varsecond);
    }
    public void Stringmthod(){
        String varname= 'Name';
        String var2name= 'Fatih';
        System.debug(varname);
        System.debug(var2name);
    }
    
}
