public  class PrimitiveDataTypeDemo2 {
    public void print1(){
        Id id1 = '0018Z00002ezgkrQAA';
        System.debug('print id = '+ id1);

        Object obj1 = 'This is a string';
        Object obj2 = 15;
        Object obj3 = '0015i00000BFSCtAAP';
        Object obj4 = true;

        system.debug('obj4 = ' + obj4);
        system.debug('obj1 = ' + obj1);
        system.debug('obj2 = ' + obj2);
        system.debug('obj3 = ' + obj3);
       

    }
}
