public  class Primitivedata_Assignment {
 public void Primitivedata_Assignment(){
    Id id1= '7018Z0000036rgwQAA';
    System.debug(id1);

    String idBlongs= ' the following id is belong to a Campaigns';
    System.debug(idBlongs);

    Boolean containCampaigns = idBlongs.contains('Campaigns');
    system.debug('has contains Campaigns '+ containCampaigns);

    system.debug(' There ios the all variable ' + id1 + idBlongs + containCampaigns );
 }

}
